### ISSUE TITLE
proper way to add onChange event while keeping redux-forms/actions?

### ISSUE THREAD

**Issue by rileylnapier** [oreqizer/redux-forms#24]
adding a onChange handler to my input seems to remove the redux-forms/actions

how do you recommend having both? using middleware to intercept the action?  use a thunk to dispatch the redux-forms/action from my onChange action?

or maybe a new function to pass into the component like "watchValue"?

thoughts?

im basically trying to call a api whenever my input field changes.  i was using onBlur... but i would like a more instant feel so im using onChange with a debounce

something like this is what i did... which i guess works?  but monkeypatching

![image](https://user-images.githubusercontent.com/7017640/30660806-f1cba4fc-9df6-11e7-8aad-ddef4233d244.png)

**Comment by oreqizer** [comment]
You can overwrite the `input.onChange` and call it manually in your handler. I did a similar thing when I wanted tracking, so I created a wrapper component.

Here's a one from scratch:

import React from 'react';
import { field } from 'redux-forms-react';

```js
class Input extends React.PureComponent {
  constructor(props) {
    super(props);

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(ev) {
    const { input } = this.props;

    console.log('Side effect :: ' + ev.target.value);
    input.onChange(ev);
  }

  render() {
    const { input } = this.props;

    return (
        <input
          {...input}
          onChange={this.handleChange}
          type="text"
        />
    );
  }
}

export default field(Input);
```

**Comment by rileylnapier** [comment]
thanks!  much nicer implementation :) . thanks 👍

**Comment by rileylnapier** [comment]
another question.  how could i listen to changes in a form?

i could create middleware and listen for "@@redux-forms/FIELD_CHANGE" and then use the getValues() selector and dispatch a new action called FORM_CHANGED?

do you think thats best?  in docs you mention don't use form action names as they may have breaking changes.

thanks for all your help

**Comment by rileylnapier** [comment]
or 

```
<Form name={myForm} onChange={(formValues) => props.doThingsWithForm(formValues)} />
```

**Comment by oreqizer** [comment]
I haven't thought about listening for changes of the _whole_ form. The only kinda clean way I can think of is comparing current and previous values in `componentWillReceiveProps`:

```js
// ...code
componentWillReceiveProps(nextProps) {
	if (this.props.values !== nextProps.values) {
		// form changed, do stuff
	}
}
// ...code

export default connect(state => ({
  values: getValues('yourform', state),
}))(YourForm);
```

I will consider introducing an API for this use case if this one turns out to be non-practical.
