### ISSUE TITLE
does REMOVE_FIELD get called when an form element gets un rendered?

### ISSUE THREAD

**Issue by rileylnapier** [oreqizer/redux-forms#25]
hi!  me again :)

i have a form with some fields that are optional, but can be flagged as required aswell.

situation is a checkout page on ecommerce where i can allow the configuration of a phone number to be required based on what country the shipping address is.

so when im USA, i don't care about phone number,
but if im Australia, i need to require phone number.  so this dynamically adds a field to my form

<Form name="myForm>
props.isInternational && <InputField name="phoneNumber" validate={required} />
</Form>

i notice that a "ADD_FIELD" action gets called when props.isInternational === true but I don't see an action to "REMOVE_FIELD".  I see its in your actions file and did a search but didn't see anywhere where you referenced it besides tests.

do i need to call this action myself?

here is example log.  REMOVE_FIELD I feel like should come after...
![image](https://user-images.githubusercontent.com/7017640/30843935-2f57516a-a241-11e7-9f07-c5869ee723cb.png)

**Comment by oreqizer** [comment]
It originally _was_ being called on unmounting, but this caused issues when used in the following way:
* Mount field A
* Fill field
* Change form - unmount & remove field A
* Change form back
* Mount field A - user has to fill again

It appeared to be a very common use case, so I removed field removal on unmount.

I can introduce a field/fieldArray API - a prop called `cleanup` that, when true, will remove the field on unmount.

What do you think?

**Comment by oreqizer** [comment]
Fixed by 1.0.0-7:
- `field` components now update on `validate` and `normalize` function changes
